import subprocess
import os
import datetime

def capture_via_subprocess(fileName):
    # The command that works in your terminal
    command = [
        "ffmpeg",
        "-y",
        "-f", "v4l2",
        "-video_size", "1920x1080",
        "-input_format", "mjpeg",
        "-i", "/dev/video0",
        "-vframes", "1",
        "-update", "1",
        "-q:v", "2",
        f"{fileName}"
    ]
    
    try:
        # Run the command and capture output (hiding the banner)
        result = subprocess.run(
            command, 
            check=True,  # Raise an exception for non-zero exit codes
            stdout=subprocess.PIPE, 
            stderr=subprocess.PIPE
        )
        print(f"Success: Image saved as '{fileName}'")
        
    except subprocess.CalledProcessError as e:
        print(f"Subprocess failed with code {e.returncode}")
        print("FFmpeg Error Output:")
        # Decode and print the FFmpeg error messages
        print(e.stderr.decode('utf8'))



def copy_file_to_share(source_file, destination_path):
    """
    Copies a file using the sudo cp command via subprocess.
    """
    
    # ⚠️ WARNING: Running commands with 'sudo' requires the user to have
    # passwordless sudo configured for this command, or the script will hang
    # waiting for a password.

    command = [
        "sudo",
        "cp",
        source_file,      # In this case: "ak1.jpeg"
        destination_path  # In this case: "windows_shared"
    ]

    try:
        # The subprocess.run() function executes the command.
        # check=True raises a CalledProcessError if the command fails.
        # capture_output=True captures stdout and stderr.
        result = subprocess.run(
            command,
            check=True,
            capture_output=True,
            text=True  # Decode output as text
        )

        print(f"✅ File copied successfully.")
        
        # You can inspect the output and errors if needed:
        # print("STDOUT:", result.stdout)
        # print("STDERR:", result.stderr)

    except subprocess.CalledProcessError as e:
        print(f"❌ Error copying file (Exit Code {e.returncode}):")
        # Print the error message generated by the shell command (e.g., file not found, permission error)
        print(e.stderr)
    except FileNotFoundError:
        print("❌ Error: 'sudo' or 'cp' command not found. Ensure commands are in the system PATH.")



destination = "./windows_shared/"

timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S_%f")
unique_filename = f"screenshot_{timestamp}.jpeg"

capture_via_subprocess(unique_filename)
copy_file_to_share(unique_filename, destination)